user_name = input('Введите свое имя: ')
title = input('Введите 3 заголовка заметки через запятую: ')
title1 = title.split(",")
content = input('Введите список выполняемых задач: ')
status = input('Подвердите статус выполнения: ')
created_date = input('Введите дату начала работы (в формате ДД.ММ.ГГГГ): ')
issue_date = input('Введите дату выполнения работы: ')

print('Имя работника:', user_name)
print('Название заметок работы:', title1)
print('Задача:', content)
print('Статус выполнения:', status)
print('Дата начала работы', created_date[:-5:])
print('Крайняя дата сдачи', issue_date[:-5:])